name: mp_predictions
description: Microplastics prediction
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  http:
  google_fonts:
  logger:
  connectivity:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  http:
  flutter_markdown: ^0.6.9+1

flutter:
  uses-material-design: true
  #Add assets:
  assets:
    - assets/pred.png
    - assets/about.jpg
    - assets/ref.jpg

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
